#!urs/bin/python
#!_*_ coding:UTF-8 _*_

from appium import webdriver


if __name__ == '__main__':
    desired_caps = {
        'platformName': 'Android',
        'deviceName': '127.0.0.1:62001',
        'platformVersion': '5.1.1',
        'appPackage': 'com.kamitu.drawsth.standalone.free.android',
        'appActivity': 'com.qsmy.busniess.welcome.WelcomeActivity'
    }
    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)



driver.find_element_by_id('com.kamitu.drawsth.standalone.free.android:id/ly').click()  #点击同意
driver.implicitly_wait(30)  #以秒为单位
driver.find_element_by_id('com.kamitu.drawsth.standalone.free.android:id/fy').click()  #点击手机号登录
driver.implicitly_wait(5)  #以秒为单位
driver.find_element_by_id('com.kamitu.drawsth.standalone.free.android:id/di').send_keys("18720102420") #输入手机号
driver.find_element_by_id('com.kamitu.drawsth.standalone.free.android:id/me').click()  #点击获取验证码
driver.implicitly_wait(120)  #以秒为单位
driver.find_element_by_id('com.kamitu.drawsth.standalone.free.android:id/b0').click()  #点击确定


